### ISSUE TITLE
Broken in PostCSS 5

### ISSUE THREAD

**Issue by onlywei** [lamo2k123/postcss-less-vars#2]
```
Your current PostCSS version is 5.0.10, but postcss-less-vars uses 4.1.14. Perhaps this is the source of the error below.

events.js:141
      throw er; // Unhandled 'error' event
```

**Comment by nchase** [comment]
Looks like you updated the PostCSS dependency in 0a276e2f but you didn't bump the version of this repo or publish a bumped version to NPM, so people who are using it are still getting the failure.

Also, it would be wiser to depend on a range of versions instead of strictly on `5.0.9` (e.g. change dependency to `"postcss": "^5.0.13"`.

Opening pull request for that shortly...

**Comment by paazmaya** [comment]
:+1: with :grapes:

**Comment by nchase** [comment]
this was merged a long time ago...if the issue is indeed fixed (and I think it is), maybe we can close the issue?

**Comment by TrySound** [comment]
@nchase There is no one release. https://github.com/lamo2k123/postcss-less-vars/compare/1.1.0...master

**Comment by nchase** [comment]
gotcha. so it was merged, but the author needs to cut a release and publish too. 😢

**Comment by lamo2k123** [comment]
npm package updated 1.2.0/
